"""empty message

Revision ID: 43e0b18403a7
Revises: 38814fff4a36
Create Date: 2022-08-13 09:32:56.721196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43e0b18403a7'
down_revision = '38814fff4a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('show', 'show_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('show', sa.Column('show_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('show', 'id')
    # ### end Alembic commands ###
